### PR TITLE
Fix #36: Exponential backoff algorithm not working correctly

### LINKED ISSUE #36: Exponential backoff algorithm not working correctly
I am running into these three issues in the current implementation:
1. If `numberOfTriesFailed` equals `1`, backoff value always equals `0`. I'd expect it to equal the `delayBetweenAttempts` parameter.
2. `backoffStrategy.getMillisToWait(5, Duration.ofMillis(100))` equals `1500`, I'd expect it to equal `1000 * 2^4` so `1600`.
3. If `numberOfTriesFailed` becomes large, backoff value becomes negative. I'd expect it to top off at max long value.

### PR DESCRIPTION
**Pull request by fdlk**

### CODE REVIEW

File: src/test/java/com/evanlennick/retry4j/backoff/BackoffStrategyTest.java [hunk 1]
```diff
@@ -5,6 +5,7 @@
 import java.time.Duration;
 
 import static org.assertj.core.api.Assertions.assertThat;
+import static org.testng.Assert.assertTrue;
```
Comment (elennick) [inline src/test/java/com/evanlennick/retry4j/backoff/BackoffStrategyTest.java]: looks like this ```assertTrue``` import got included accidentally, can you remove it?
